// Objective-C API for talking to github.com/fatedier/frp/cmd/frpc Go package.
//   gobind -lang=objc github.com/fatedier/frp/cmd/frpc
//
// File is generated by gobind. Do not edit.

#ifndef __Frpclib_H__
#define __Frpclib_H__

@import Foundation;
#include "Universe.objc.h"


// skipped function HandleSignal with unsupported parameter or return types


FOUNDATION_EXPORT void FrpclibRun(NSString* confFile);

#endif
